[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "ee3686627d7537b97d17f82ac365f7a468c608f0"
os = "macos"

    [[DataEcon.download]]
    sha256 = "ad808ad0db817bfbee7b8ca04e2bf0a76e7dd318977247c9a7bec433d76fb99b"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.aarch64-apple-darwin.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "716f222b1cc74953eab0b4dfec24f4981269c7e7"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "652375b6813f989c38e70d1bb6deacedbc367363757b6184032e34271095af26"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.aarch64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "3ed441af48b05417fd67a6187203d063fd644004"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "ca16e24af3203e77f93bdeb99f4a54820156ffff640d93f083480857f1f8c814"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.aarch64-linux-musl.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "b04dfe28aa67513bd4929b7db9953a48dd39ec48"
os = "freebsd"

    [[DataEcon.download]]
    sha256 = "4dbaa4d562c857cd887dd4b9f9c1298396af6c33bff01b2a279ae375e3e7a8e4"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.aarch64-unknown-freebsd.tar.gz"
[[DataEcon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bbb595b6dda42aa323c1833d813dab3574eb0612"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "be780eb6cfe291b2b54f0952e03a4ddfe8818b6d8fa490a6c9bd59a1814d935e"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.armv6l-linux-gnueabihf.tar.gz"
[[DataEcon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f9fadcf95e34ea208142bee55e1ced187fc8aa41"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "58e0247ab1c8ca1994c414c4e08bf0cdc9e1bab8224ffaed06e308000680f917"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.armv6l-linux-musleabihf.tar.gz"
[[DataEcon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8f1c51e2d119395e3dfe3c3013d1e56f42fedf22"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "ec68df0e4c421b3d029e37894f7382537f076a8c035d1aa1ccd7c60b660c86c0"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.armv7l-linux-gnueabihf.tar.gz"
[[DataEcon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "45bfe57a54a7df7880011e83d6b98a66d20a14ad"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "c78d23c094421bb8784ae88bfd31f319eace89328ab7fdf8a3d0c8caf391cbeb"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.armv7l-linux-musleabihf.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "68f636a97b9ac80dd6ef0b1996e2e596ee8b1d87"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "f7002002802d8d1030a738c9c461d2881c823e71aae15bcb13dc909cff5883f2"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.i686-linux-gnu.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "69ab816bfa233e3442b6e3627813de83c51fb9bb"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "42a25f98223f7cc5f8055b6805945067dd77ba82f9fe4a625e7def17030ee088"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.i686-linux-musl.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "34a7f6d38a409d424c1fe40d1f5952214646310a"
os = "windows"

    [[DataEcon.download]]
    sha256 = "7bac2ff053be81971360742f9efc5a8824b93f1638a95a281c985bbc178f3bcc"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.i686-w64-mingw32.tar.gz"
[[DataEcon]]
arch = "powerpc64le"
git-tree-sha1 = "96e6836d0bc8e29292a52d66d40f4b05f2201c02"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "e91d43955f4ff910fca7e48b238fb2f809b719fe1e78281742b00265acfdc77a"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[DataEcon]]
arch = "riscv64"
git-tree-sha1 = "32f35d637274401220d147d0dad0ee9006c767d5"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "6a0bc919b97581a53a62fcb660a95b862fc40e21ebdb6befa12d812bf9b0be0a"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.riscv64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "3ea0e70a8bd510eda2b780d33391bd5da64d478b"
os = "macos"

    [[DataEcon.download]]
    sha256 = "92a574604b83798c12831c13918ee18cb43509c469476baf8ab85a73a53cb342"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.x86_64-apple-darwin.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "9da7620d21badddd9329701442e49f9c1dd6919f"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "5306776a09e015e7c8312d36f68f9fa21aa706454dc681a390638bcedc7ad17f"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.x86_64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "7dee01f91ad73cb39eaadfeac736ac8a4babb806"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "a1aa71d3b1d0e552f4bf0cec9d94df182e67e0d5a93aefa81bdb8126ca840183"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.x86_64-linux-musl.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "ca831278787d7e47e08e3aa0b2ffe2ab2b36014c"
os = "freebsd"

    [[DataEcon.download]]
    sha256 = "281a3191f865ec42d865916671164613d67ab01301132e229d9603be71091b2d"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.x86_64-unknown-freebsd.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "5ddd4df4a740209b3c20d4cf9c5d1a45c3f1f855"
os = "windows"

    [[DataEcon.download]]
    sha256 = "c4d965008d46ab204fa35bbaee3238f3a15393850f0993e1d3cda52dba9af465"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.4.0+0/DataEcon.v0.4.0.x86_64-w64-mingw32.tar.gz"
