[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "22865d22dc81be54f318e5f781cf3fe17d6a515f"
os = "macos"

    [[DataEcon.download]]
    sha256 = "6f6d781444c8416c4a58529de4d2117ff835f1242564000534aa685667cf88ec"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.aarch64-apple-darwin.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "ee5437e205effbd6a12cd4693d0bc2b5c8fdeb6f"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "df30471abb328022469edacf11a07912e751675af1cd3d2fde20cad67d727df7"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.aarch64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "385124d5653d3159e38ee3a96bdaec01af184370"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "acd9207327727df1710b4182ae2026d69befa99bb6cbe91f123bcd5c4c135788"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.aarch64-linux-musl.tar.gz"
[[DataEcon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "304c9421610a7508d5e6ee3d0a311a0f7a76901b"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "e8153516e778f4bc37e447c6b175e63ca39436d25abaccdc490ebb8f8dcd2926"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.armv6l-linux-gnueabihf.tar.gz"
[[DataEcon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce48a37455743747a686b5afefdb231052ecf3a8"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "46fa3ba113dabfd24132abb4ca3dd2fb922f3b87266f15a98fb8107a70d27f93"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.armv6l-linux-musleabihf.tar.gz"
[[DataEcon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94f23e13a0226966c9233de3b820a6b3bb5ba239"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "bc666632814ef35d5b792cec3aa2af6451c08ae92046cf5d94021d8667771828"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.armv7l-linux-gnueabihf.tar.gz"
[[DataEcon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da28d933f0379ec0d0e0d0738f621a0929ecf4ef"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "439d424c27679f88d9b1efb182cde5b0e00fa72bb9c23d4e41786a97baa3c2f8"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.armv7l-linux-musleabihf.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "a0b75fafafa5f5cb710df3fa60a6e927c03b2e63"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "60a39813d51e50ca37232dad06fa10c426642a12ad91eb0140c7aaac4e2459be"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.i686-linux-gnu.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "e5b5f54ae0f7a3cd7e00fdfc5b7ca85cabec3a69"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "8ac2122d2a8d86e2869dd0415538295de239725fa3bde2204e293c742a08da4d"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.i686-linux-musl.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "e1753d19b9cbbf8afafd50aad082916bcb3b041f"
os = "windows"

    [[DataEcon.download]]
    sha256 = "ce5913d0af6d54652d367b22acc0cf099b1002cd4b6c0ab974568cd785fd8a44"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.i686-w64-mingw32.tar.gz"
[[DataEcon]]
arch = "powerpc64le"
git-tree-sha1 = "fbec6b9ebed2f726780eb2aa509562a3b1f62d82"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "320c062469cd1c57a84386994655c174ad0df0d46f8a3be177e094d09bd2d6a8"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.powerpc64le-linux-gnu.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "d76074ffda48bbf0bcc6b218425d06acd76d1642"
os = "macos"

    [[DataEcon.download]]
    sha256 = "07b1875276fee65b5b122d4a8a257941e569fbd00e827cc7ae26c6352554827c"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.x86_64-apple-darwin.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "9e532c4cc7a2c7799dc3d3c91c3cb2d8d9d2a3df"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "f307b80f4ad5ed82b6f1fe46986b1e4a8708be8fd774269eb370eabf2277a82c"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.x86_64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "dc01e22e4da29c18e550a6ca17c62da4af073189"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "1adedb2cf644dbf55208c2f5902546e65f2d884e50795fcfab278b343c62815f"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.x86_64-linux-musl.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "6966bde1995e59ab268d78aba45e2247d4191e74"
os = "freebsd"

    [[DataEcon.download]]
    sha256 = "dd732ca89f26026bea633fb2cf050d61edadaf4a14c1cb99877103af6abcfeef"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.x86_64-unknown-freebsd.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "7a1d350cee67f411e8e81d4eadbf1cc6e2adc6e0"
os = "windows"

    [[DataEcon.download]]
    sha256 = "2f59d56b58860505973f99c921e0cb21e37568a64beb42d803a7fc16ba596692"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.2+0/DataEcon.v0.2.2.x86_64-w64-mingw32.tar.gz"
