[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "417f2cdb4d15b097b2d1cef1212af478beade37a"
os = "macos"

    [[DataEcon.download]]
    sha256 = "43e43e6927699b19db2306596dcb9805474e3512c646e6b631c5ff3cc77bdbc6"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.aarch64-apple-darwin.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "ecdfd869386aa61e22479f96760e0ca8cae75ab1"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "4121320a96167fce6fb6378be6acbbbd71a9d19df703164fec852c5da8dfa024"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.aarch64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "06df7b72f2002299b252757cdf1e0fc26dcf6d5b"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "7dbe3d89fa180291b74bc169696e1c4d326bc94fe57ae8b774c9f9e9563d54be"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.aarch64-linux-musl.tar.gz"
[[DataEcon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0cea76ddf9efba73f8ce0cf49a7bd77122931a75"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "89cbc2935762ddf18a54ac247033b25d53bbadadead7d5fde03bf5c903ea8efb"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.armv6l-linux-gnueabihf.tar.gz"
[[DataEcon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b97916adcb5797baa63da76f77d018e144fec531"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "a8f1977401935967baa3e8fd303ddf003141cf4a3a3cb69d6b87a6211c1fefc9"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.armv6l-linux-musleabihf.tar.gz"
[[DataEcon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5c5afecd31f55123b98858aa6cd28f165f30fe77"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "8e391c1a00b160d83e2d9f709a79e65e4ca180cab6982378597ff759a520cd1a"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.armv7l-linux-gnueabihf.tar.gz"
[[DataEcon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "757b016058c92ab7143a06e3b1bb2ae514990f1b"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "40608af5c9731fea999648595b634de0a167dcbacc27a8abbdfca4a75fe633a7"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.armv7l-linux-musleabihf.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "f470186a5e87550195561e060452831bf81da50a"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "aa64c6c170ec279491b039fe4f810a075795ee4bf977a3bd1c9b8d1b3ba410da"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.i686-linux-gnu.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "b0a6f0c02545a6dff2c4b5d0cb7779930dcbb464"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "89e70856857d1c717593bd313520afe9260b1a6b2a7c4bef59a1bb142bfe90b6"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.i686-linux-musl.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "8adcadb3384748f3541d44af49c24168e5d9b399"
os = "windows"

    [[DataEcon.download]]
    sha256 = "9bb18c3d9f401e39924805bfef33d32773e29d3746ad4faaa104f451865b0633"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.i686-w64-mingw32.tar.gz"
[[DataEcon]]
arch = "powerpc64le"
git-tree-sha1 = "0e748bbd665b08ae3eb2d3aabb352990f4ccca9a"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "39d2f04b0a913cdd9d34a9a5021901cbcac1fabf735f005bbb7bbe1f33820f30"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.powerpc64le-linux-gnu.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "e7c8ed3d670abb0bbeae5a2e2b5ae52651ed46b8"
os = "macos"

    [[DataEcon.download]]
    sha256 = "60a423761863ba252477e20f1c20a8f7c444e2100348e315efff0cd06014f50a"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.x86_64-apple-darwin.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "4ceb2311699addf2e080062c33b34d801dd23120"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "c3a22a17ec886a86ce369526cbd6a9c23e311c0af96060f15d5f8d871cb87c6d"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.x86_64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "3ce8166d7b5740833e92b6a7b1f10dc5817bacbf"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "b5078d8b481766d169705a5d42fa56734d819d61c9bafc8296fcf552f7f1c7f6"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.x86_64-linux-musl.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "4fc9b93ce9c4b2485ec2db756028592d9cb333a4"
os = "freebsd"

    [[DataEcon.download]]
    sha256 = "598537b9764efc2f162b702de1bf1706c86b535124c3bcf6687f2bfd6c684782"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.x86_64-unknown-freebsd.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "37dc151cc14ef982e75fcf277a770683805e5849"
os = "windows"

    [[DataEcon.download]]
    sha256 = "9f671cf620ff09fd59554fc0bb129d62c18c51d852e29fa1a4fbb462e61cfec1"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.2.1+0/DataEcon.v0.2.1.x86_64-w64-mingw32.tar.gz"
