[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "bd6d37342c26bf00957c91591442f516db5e63f9"
os = "macos"

    [[DataEcon.download]]
    sha256 = "1d624e1815abaec83117397a9a4df6d4554401d65d40621d4b64bbd5ae6ecf03"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.aarch64-apple-darwin.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "eae707b7839a781a006e29bb0dc001ba0ae20d84"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "4755671b2e1341e1dcd810fb92b6b6266a46f80d5c03294fa34bae4f0406d447"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.aarch64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "7a2dfa19a85ff282038c8978aa0402c9ddf9af67"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "db0da9a7238fe5ee83d4793718b88d2a67614317aa575001b1854dcc64c0c612"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.aarch64-linux-musl.tar.gz"
[[DataEcon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8995630936a7c99f0dd82a4795b91db829f68073"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "6f9a50b0b4f652a4c9bb669dd6041eceed39cbe0b5a23be9348623e2fda5de48"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.armv6l-linux-gnueabihf.tar.gz"
[[DataEcon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "44acd14f6020f7687c31c7ac36032329b8481e0a"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "ea306c24d378d30ea07ec25935b5063561760d5f61258e0a389a472b4d05a202"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.armv6l-linux-musleabihf.tar.gz"
[[DataEcon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "95e98f9e6115771e678f60bdc7c5e6d4f526ae4c"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "26cebe717f225b6a78ba799dfe831325569d6a393f3f053bf66707087cf20c3a"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.armv7l-linux-gnueabihf.tar.gz"
[[DataEcon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "efb6989914b4b309b7c6a4a5459402872ce6c40d"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "c9c3d1ccd0fc5a8a09a899d846a3d11aca69cbcc6d72b27bf3b97fa9c22045ab"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.armv7l-linux-musleabihf.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "a4e909279e8fe072905ec67de7f06097b173f670"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "f7880694523dae3f5d25b680164dec6f7b1e9b6e5bb3ff863e7db77439c89f57"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.i686-linux-gnu.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "853d4e2a0e562b57ca74f504f68899db2d4c6915"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "9c19eda9dd473219af5ebaf5e0f1f9134c0b8b8d1ce3bec777d84391f7821fff"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.i686-linux-musl.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "26ec17a19144a729f18ad2c55df73ab049882a0d"
os = "windows"

    [[DataEcon.download]]
    sha256 = "123f31c18a1e3454c14891773bebf44d8c1f722995f8bf0406fd3872ce8250d6"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.i686-w64-mingw32.tar.gz"
[[DataEcon]]
arch = "powerpc64le"
git-tree-sha1 = "e4895b174f520ebcca286b584de346bfdfdcca85"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "715de45d1b4a14b4a0a6c6d3c012f5a0d2d18680e19128422012752212907a6c"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.powerpc64le-linux-gnu.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "7e3bdcc7f3bd241dc54f944fd9d78008c8c1a670"
os = "macos"

    [[DataEcon.download]]
    sha256 = "f6d0c27395f020acee5d221f752a8da6f27c3183ce50b03ed2418f600cb310a5"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.x86_64-apple-darwin.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "04c2c7492cd339b22112fdcbc28c748112e699b9"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "95fae82cbdb60de42f0adcf1ccc5ec89d956e9a2ea472b3f769896ec37127fbc"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.x86_64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "b1bf6d9a5a6c99c18c61c186791f214facf8cbcd"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "cd6d468c72c266b665c4f5bb471a445776b02e2620371f60508e763be2e32798"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.x86_64-linux-musl.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "44a995b52680005b48891bd966b6262218094bb1"
os = "freebsd"

    [[DataEcon.download]]
    sha256 = "efcf5351b244b7c519229be67ab022015573345bfb82c1ecca77a48b170fae22"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.x86_64-unknown-freebsd.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "e466744958fa3248589f006b1a76f9e386e213a2"
os = "windows"

    [[DataEcon.download]]
    sha256 = "220dea62df14adc03e256449b512480b623f64a4fa2f10c4ca753c1b9a37e266"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.1+0/DataEcon.v0.3.1.x86_64-w64-mingw32.tar.gz"
