[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "4b1a484467a82da00ac6a8b1ea01dd74314bb75e"
os = "macos"

    [[DataEcon.download]]
    sha256 = "5ba63cfe05b3a12624b3ad19a4f1edd1991c3e7323c127d02c1db31e6a21436c"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.aarch64-apple-darwin.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "8a9c18782e82db525b63b7ef463eca205be094d1"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "ec15bf8f57f3386acf3df2e44dc4186b5c137d280cfa305d020809b1df4fc867"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.aarch64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "ac2b7ee445f12dfff71741d32dd5297fae4b2442"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "8a7e893c50f89e82f89c83b7f6cc5564ecc1558ca2c6c704f4257dd4c00e662e"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.aarch64-linux-musl.tar.gz"
[[DataEcon]]
arch = "aarch64"
git-tree-sha1 = "b1ea4b16b8cbb14da42784c02ee654159db50a45"
os = "freebsd"

    [[DataEcon.download]]
    sha256 = "0d687df87237ef262e561aa5c24d812e22409f30c9b3ca3e68b9f2edcc5d7b6f"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.aarch64-unknown-freebsd.tar.gz"
[[DataEcon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ef300f50304779a63222e200b6b3ad04acb9f8b1"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "47482fa1772597f2c9b9fe25aa65fb5633b1087017a97fc025c7bf6a7c7f7ef2"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.armv6l-linux-gnueabihf.tar.gz"
[[DataEcon]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "99545130928afac81ccedfd79f4ad3fc92166b17"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "10177588ae4fa0732de0d477f4163caafeeb6c99620dd7036d1a0c07d25b47fc"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.armv6l-linux-musleabihf.tar.gz"
[[DataEcon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f1e00c8d3a27b5729b3520970f85b335f43fe0c"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "33818e31fae46c85dff8260c590f6db48296660c85bbc3f88e4217525ab3a5e2"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.armv7l-linux-gnueabihf.tar.gz"
[[DataEcon]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "631855b20219c4e2aa04fb2775328e4badb32541"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "9c4bd65cc6e3ccd317c6a3722c20df8e6d0e1b437ca9ac0332fcbce1f789c538"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.armv7l-linux-musleabihf.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "c2bd370807fbeca653ed62c5a72f5d0177f3aac0"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "3d1d380000197b4cf2e65731449ea300f8b5e1af5bd045ff06f727baafdd2b90"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.i686-linux-gnu.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "0e5492e00361213b7d15db807b990de696878dbd"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "e36cb99381eed890df33085b92181e8964589a89aec33dd86372e895d8b9c55f"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.i686-linux-musl.tar.gz"
[[DataEcon]]
arch = "i686"
git-tree-sha1 = "565d95ed79453ad78933c7533deed4707120b90a"
os = "windows"

    [[DataEcon.download]]
    sha256 = "8902a77f5e6094251c1da357b540f69454002133badf4de9fa92507c1c86cece"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.i686-w64-mingw32.tar.gz"
[[DataEcon]]
arch = "powerpc64le"
git-tree-sha1 = "79818b562d436bb4d9d62fd3b30b0a875e5b4086"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "58562b635de394ed7961b14daec8fb6839ece63ceca1318485dd33bc495073c9"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.powerpc64le-linux-gnu.tar.gz"
[[DataEcon]]
arch = "riscv64"
git-tree-sha1 = "3cd6893252d25a01f189572504a98d5425dd6342"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "5ff955f31a7263e71872cea26ad06c3065bf3e211423d8f102f66a64d886fedf"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.riscv64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "1513ac0357250f9034f8ea8e14ce2fc6eaace5fd"
os = "macos"

    [[DataEcon.download]]
    sha256 = "5c7331b36465628ef200ccfae601c9e1cb295774f0bcb8c1835d9b290d1e12ab"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.x86_64-apple-darwin.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "9eaa13ea85b4c3953c5383403d5abd42da228969"
libc = "glibc"
os = "linux"

    [[DataEcon.download]]
    sha256 = "5e987eeb9171b1fe028ee580618fea76ba40e7ac491cafbc98949df6785ad078"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.x86_64-linux-gnu.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "5c2117dfe4e605249f40e3a6cbbd923bcb9792f5"
libc = "musl"
os = "linux"

    [[DataEcon.download]]
    sha256 = "7eef72b6d3d6e1f5185ef6f655089f2e90bbf9f39e6edf2c19165f47d08337f4"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.x86_64-linux-musl.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "31f519c12782ef013acf355f38cb9db8e7e83b22"
os = "freebsd"

    [[DataEcon.download]]
    sha256 = "fd4c1dfcdd35b438f30af4e35a3df23b9ec7c7bd10af7b775834b4036c76586c"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.x86_64-unknown-freebsd.tar.gz"
[[DataEcon]]
arch = "x86_64"
git-tree-sha1 = "c1bd2621920d138f7c7ecc57c32a96f560b71612"
os = "windows"

    [[DataEcon.download]]
    sha256 = "688917d847ea0d712df96c314b5bb074eeb47fdb2d2fdcee377cbebc669f8dc6"
    url = "https://github.com/JuliaBinaryWrappers/DataEcon_jll.jl/releases/download/DataEcon-v0.3.2+0/DataEcon.v0.3.2.x86_64-w64-mingw32.tar.gz"
